male(jim).
male(george).
female(pat).
female(helen).
female(maka).
father(tom).
father(cons).
mother(ann).
mother(maria).
unemployed(pat).
unemployed(jim).
unemployed(george).
unemployed(helen).
unemployed(maka).
person(man,full_name(tom,fox),dateborn(7,may,1950),works(bbc,15200)).
person(female,full_name(ann,fox),dateborn(9,may,1951),unemployed).
person(man,full_name(cons,kal),dateborn(30,june,1952),works(bbc,30200)).
person(female,full_name(maria,kal),dateborn(27,june,1955),unemployed).
birthday_date(pat,5,may,1973).
birthday_date(jim,5,may,1973).
birthday_date(george,23,may,1975).
birthday_date(helen,12,june,1973).
birthday_date(maka,12,june,1973).
family(tom,ann,[pat,jim]).
family(cons,maria,[george,helen,maka]). 
child(X):-family(_,_,Children),member(X,Children).
dateofbirth(child(X),1973):-birthday_date(X,_,_,1973).